repository:
  # current: true
  # url: https://github.medallia.com/Atlas/deployment
  url: https://github.medallia.com/stellaservice/jenkins-testing
  apiBaseUrl: https://github.medallia.com/api/v3 # Required for GH enterprise

fileSyncs:
  # UpdateWebImageProduction:
  #   type: 'regex'
  #   target: '(tag:) [0-9].[0-9].[0-9]-pre-\w{7}-[0-9]{13}'
  #   replacementValue: '$1 {{{image_tag}}}'
  #   files:
  #     - 'apps/stella/connect/values/fra1/stella-connect-1/connect-web.yaml'
  #     - 'apps/stella/connect/values/sea1/stella-connect-1/connect-web.yaml'
  # UpdateWebImagePreprod:
  #   type: 'regex'
  #   target: '(tag:) [0-9].[0-9].[0-9]-pre-\w{7}-[0-9]{13}'
  #   replacementValue: '$1 {{{image_tag}}}'
  #   files:
  #     - 'apps/stella/connect/values/den/stella-connect-1/connect-web.yaml'
  # UpdateWebImageProduction:
  #   type: 'yaml'
  #   target: '["connect-web"].image.tag'
  #   # target: '.image.tag'
  #   replacementValue: {{{image_tag}}}
  #   files:
  #     - '../deployment/apps/stella/connect/values/fra1/stella-connect-1/connect-web.yaml'
  #     - '../deployment/apps/stella/connect/values/sea1/stella-connect-1/connect-web.yaml'
  TestYamlUpdate:
    type: 'yaml'
    target: '.image.tag'
    value: {{{image_tag}}}
    files:
      - './test.yaml'

jobs:
  # - name: StellaConnectUpdateWebImageProduction # Make this name unique (collisions for the same repo & base branch can be dangerous)
  #   fileSync: UpdateWebImageProduction
  #   branch: master
  # - name: StellaConnectUpdateWebImagePreprod
  #   fileSync: UpdateWebImagePreprod
  #   branch: preprod
  - name: TestYamlUpdate
    fileSync: TestYamlUpdate
    branch: master

