repository:
  current: true

fileSyncs:
  UpdateWebImage:
    type: 'yaml'
    target: '["connect-web"].image.tag'
    # target: '.image.tag'
    replacementValue: {{{image_tag}}}
    files:
      - '../deployment/apps/stella/connect/values/fra1/stella-connect-1/connect-web.yaml'
      # - '../deployment/apps/stella/connect/values/sea1/stella-connect-1/connect-web.yaml'
      # - './dummy_file.yaml'

jobs:
  - file_sync: UpdateWebImage
    branches:
      - master
      - preprod
