version: 2.1

executors:
  node:
    docker:
      - image: node:14.17.6-stretch

jobs:
  ci:
    executor: node
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn jest

workflows:
  version: 2
  workflow:
    jobs:
      - ci
