name: ci
on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-20.04
    container:
      image: node:18.16.0-buster
      options: -u root
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run jest specs
        run: npx jest
